/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// Attributes struct for Attributes
type Attributes struct {
	MfaAuthenticated string `json:"mfaAuthenticated"`
	CreationDate time.Time `json:"creationDate"`
}

// NewAttributes instantiates a new Attributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributes(mfaAuthenticated string, creationDate time.Time, ) *Attributes {
	this := Attributes{}
	this.MfaAuthenticated = mfaAuthenticated
	this.CreationDate = creationDate
	return &this
}

// NewAttributesWithDefaults instantiates a new Attributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributesWithDefaults() *Attributes {
	this := Attributes{}
	return &this
}

// GetMfaAuthenticated returns the MfaAuthenticated field value
func (o *Attributes) GetMfaAuthenticated() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.MfaAuthenticated
}

// GetMfaAuthenticatedOk returns a tuple with the MfaAuthenticated field value
// and a boolean to check if the value has been set.
func (o *Attributes) GetMfaAuthenticatedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MfaAuthenticated, true
}

// SetMfaAuthenticated sets field value
func (o *Attributes) SetMfaAuthenticated(v string) {
	o.MfaAuthenticated = v
}

// GetCreationDate returns the CreationDate field value
func (o *Attributes) GetCreationDate() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value
// and a boolean to check if the value has been set.
func (o *Attributes) GetCreationDateOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreationDate, true
}

// SetCreationDate sets field value
func (o *Attributes) SetCreationDate(v time.Time) {
	o.CreationDate = v
}

func (o Attributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mfaAuthenticated"] = o.MfaAuthenticated
	}
	if true {
		toSerialize["creationDate"] = o.CreationDate
	}
	return json.Marshal(toSerialize)
}

type NullableAttributes struct {
	value *Attributes
	isSet bool
}

func (v NullableAttributes) Get() *Attributes {
	return v.value
}

func (v *NullableAttributes) Set(val *Attributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributes(val *Attributes) *NullableAttributes {
	return &NullableAttributes{value: val, isSet: true}
}

func (v NullableAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


