/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// AWSAPICallViaCloudTrail struct for AWSAPICallViaCloudTrail
type AWSAPICallViaCloudTrail struct {
	RequestParameters NullableRequestParameters `json:"requestParameters"`
	UserIdentity UserIdentity `json:"userIdentity"`
	EventID string `json:"eventID"`
	AwsRegion string `json:"awsRegion"`
	EventVersion string `json:"eventVersion"`
	ResponseElements map[string]interface{} `json:"responseElements"`
	SourceIPAddress string `json:"sourceIPAddress"`
	EventSource string `json:"eventSource"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty"`
	UserAgent string `json:"userAgent"`
	EventType string `json:"eventType"`
	ApiVersion *string `json:"apiVersion,omitempty"`
	RequestID string `json:"requestID"`
	EventTime time.Time `json:"eventTime"`
	EventName string `json:"eventName"`
}

// NewAWSAPICallViaCloudTrail instantiates a new AWSAPICallViaCloudTrail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSAPICallViaCloudTrail(requestParameters NullableRequestParameters, userIdentity UserIdentity, eventID string, awsRegion string, eventVersion string, responseElements map[string]interface{}, sourceIPAddress string, eventSource string, userAgent string, eventType string, requestID string, eventTime time.Time, eventName string, ) *AWSAPICallViaCloudTrail {
	this := AWSAPICallViaCloudTrail{}
	this.RequestParameters = requestParameters
	this.UserIdentity = userIdentity
	this.EventID = eventID
	this.AwsRegion = awsRegion
	this.EventVersion = eventVersion
	this.ResponseElements = responseElements
	this.SourceIPAddress = sourceIPAddress
	this.EventSource = eventSource
	this.UserAgent = userAgent
	this.EventType = eventType
	this.RequestID = requestID
	this.EventTime = eventTime
	this.EventName = eventName
	return &this
}

// NewAWSAPICallViaCloudTrailWithDefaults instantiates a new AWSAPICallViaCloudTrail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSAPICallViaCloudTrailWithDefaults() *AWSAPICallViaCloudTrail {
	this := AWSAPICallViaCloudTrail{}
	return &this
}

// GetRequestParameters returns the RequestParameters field value
// If the value is explicit nil, the zero value for RequestParameters will be returned
func (o *AWSAPICallViaCloudTrail) GetRequestParameters() RequestParameters {
	if o == nil || o.RequestParameters.Get() == nil {
		var ret RequestParameters
		return ret
	}

	return *o.RequestParameters.Get()
}

// GetRequestParametersOk returns a tuple with the RequestParameters field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AWSAPICallViaCloudTrail) GetRequestParametersOk() (*RequestParameters, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RequestParameters.Get(), o.RequestParameters.IsSet()
}

// SetRequestParameters sets field value
func (o *AWSAPICallViaCloudTrail) SetRequestParameters(v RequestParameters) {
	o.RequestParameters.Set(&v)
}

// GetUserIdentity returns the UserIdentity field value
func (o *AWSAPICallViaCloudTrail) GetUserIdentity() UserIdentity {
	if o == nil  {
		var ret UserIdentity
		return ret
	}

	return o.UserIdentity
}

// GetUserIdentityOk returns a tuple with the UserIdentity field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetUserIdentityOk() (*UserIdentity, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserIdentity, true
}

// SetUserIdentity sets field value
func (o *AWSAPICallViaCloudTrail) SetUserIdentity(v UserIdentity) {
	o.UserIdentity = v
}

// GetEventID returns the EventID field value
func (o *AWSAPICallViaCloudTrail) GetEventID() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.EventID
}

// GetEventIDOk returns a tuple with the EventID field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetEventIDOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventID, true
}

// SetEventID sets field value
func (o *AWSAPICallViaCloudTrail) SetEventID(v string) {
	o.EventID = v
}

// GetAwsRegion returns the AwsRegion field value
func (o *AWSAPICallViaCloudTrail) GetAwsRegion() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AwsRegion
}

// GetAwsRegionOk returns a tuple with the AwsRegion field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetAwsRegionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AwsRegion, true
}

// SetAwsRegion sets field value
func (o *AWSAPICallViaCloudTrail) SetAwsRegion(v string) {
	o.AwsRegion = v
}

// GetEventVersion returns the EventVersion field value
func (o *AWSAPICallViaCloudTrail) GetEventVersion() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.EventVersion
}

// GetEventVersionOk returns a tuple with the EventVersion field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetEventVersionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventVersion, true
}

// SetEventVersion sets field value
func (o *AWSAPICallViaCloudTrail) SetEventVersion(v string) {
	o.EventVersion = v
}

// GetResponseElements returns the ResponseElements field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *AWSAPICallViaCloudTrail) GetResponseElements() map[string]interface{} {
	if o == nil  {
		var ret map[string]interface{}
		return ret
	}

	return o.ResponseElements
}

// GetResponseElementsOk returns a tuple with the ResponseElements field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AWSAPICallViaCloudTrail) GetResponseElementsOk() (*map[string]interface{}, bool) {
	if o == nil || o.ResponseElements == nil {
		return nil, false
	}
	return &o.ResponseElements, true
}

// SetResponseElements sets field value
func (o *AWSAPICallViaCloudTrail) SetResponseElements(v map[string]interface{}) {
	o.ResponseElements = v
}

// GetSourceIPAddress returns the SourceIPAddress field value
func (o *AWSAPICallViaCloudTrail) GetSourceIPAddress() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.SourceIPAddress
}

// GetSourceIPAddressOk returns a tuple with the SourceIPAddress field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetSourceIPAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceIPAddress, true
}

// SetSourceIPAddress sets field value
func (o *AWSAPICallViaCloudTrail) SetSourceIPAddress(v string) {
	o.SourceIPAddress = v
}

// GetEventSource returns the EventSource field value
func (o *AWSAPICallViaCloudTrail) GetEventSource() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.EventSource
}

// GetEventSourceOk returns a tuple with the EventSource field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetEventSourceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventSource, true
}

// SetEventSource sets field value
func (o *AWSAPICallViaCloudTrail) SetEventSource(v string) {
	o.EventSource = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *AWSAPICallViaCloudTrail) GetErrorMessage() string {
	if o == nil || o.ErrorMessage == nil {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetErrorMessageOk() (*string, bool) {
	if o == nil || o.ErrorMessage == nil {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *AWSAPICallViaCloudTrail) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage != nil {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *AWSAPICallViaCloudTrail) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *AWSAPICallViaCloudTrail) GetErrorCode() string {
	if o == nil || o.ErrorCode == nil {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetErrorCodeOk() (*string, bool) {
	if o == nil || o.ErrorCode == nil {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *AWSAPICallViaCloudTrail) HasErrorCode() bool {
	if o != nil && o.ErrorCode != nil {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *AWSAPICallViaCloudTrail) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetUserAgent returns the UserAgent field value
func (o *AWSAPICallViaCloudTrail) GetUserAgent() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetUserAgentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserAgent, true
}

// SetUserAgent sets field value
func (o *AWSAPICallViaCloudTrail) SetUserAgent(v string) {
	o.UserAgent = v
}

// GetEventType returns the EventType field value
func (o *AWSAPICallViaCloudTrail) GetEventType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetEventTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *AWSAPICallViaCloudTrail) SetEventType(v string) {
	o.EventType = v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *AWSAPICallViaCloudTrail) GetApiVersion() string {
	if o == nil || o.ApiVersion == nil {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetApiVersionOk() (*string, bool) {
	if o == nil || o.ApiVersion == nil {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *AWSAPICallViaCloudTrail) HasApiVersion() bool {
	if o != nil && o.ApiVersion != nil {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *AWSAPICallViaCloudTrail) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetRequestID returns the RequestID field value
func (o *AWSAPICallViaCloudTrail) GetRequestID() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.RequestID
}

// GetRequestIDOk returns a tuple with the RequestID field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetRequestIDOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RequestID, true
}

// SetRequestID sets field value
func (o *AWSAPICallViaCloudTrail) SetRequestID(v string) {
	o.RequestID = v
}

// GetEventTime returns the EventTime field value
func (o *AWSAPICallViaCloudTrail) GetEventTime() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.EventTime
}

// GetEventTimeOk returns a tuple with the EventTime field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetEventTimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventTime, true
}

// SetEventTime sets field value
func (o *AWSAPICallViaCloudTrail) SetEventTime(v time.Time) {
	o.EventTime = v
}

// GetEventName returns the EventName field value
func (o *AWSAPICallViaCloudTrail) GetEventName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *AWSAPICallViaCloudTrail) GetEventNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *AWSAPICallViaCloudTrail) SetEventName(v string) {
	o.EventName = v
}

func (o AWSAPICallViaCloudTrail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["requestParameters"] = o.RequestParameters.Get()
	}
	if true {
		toSerialize["userIdentity"] = o.UserIdentity
	}
	if true {
		toSerialize["eventID"] = o.EventID
	}
	if true {
		toSerialize["awsRegion"] = o.AwsRegion
	}
	if true {
		toSerialize["eventVersion"] = o.EventVersion
	}
	if o.ResponseElements != nil {
		toSerialize["responseElements"] = o.ResponseElements
	}
	if true {
		toSerialize["sourceIPAddress"] = o.SourceIPAddress
	}
	if true {
		toSerialize["eventSource"] = o.EventSource
	}
	if o.ErrorMessage != nil {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if true {
		toSerialize["userAgent"] = o.UserAgent
	}
	if true {
		toSerialize["eventType"] = o.EventType
	}
	if o.ApiVersion != nil {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if true {
		toSerialize["requestID"] = o.RequestID
	}
	if true {
		toSerialize["eventTime"] = o.EventTime
	}
	if true {
		toSerialize["eventName"] = o.EventName
	}
	return json.Marshal(toSerialize)
}

type NullableAWSAPICallViaCloudTrail struct {
	value *AWSAPICallViaCloudTrail
	isSet bool
}

func (v NullableAWSAPICallViaCloudTrail) Get() *AWSAPICallViaCloudTrail {
	return v.value
}

func (v *NullableAWSAPICallViaCloudTrail) Set(val *AWSAPICallViaCloudTrail) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSAPICallViaCloudTrail) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSAPICallViaCloudTrail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSAPICallViaCloudTrail(val *AWSAPICallViaCloudTrail) *NullableAWSAPICallViaCloudTrail {
	return &NullableAWSAPICallViaCloudTrail{value: val, isSet: true}
}

func (v NullableAWSAPICallViaCloudTrail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSAPICallViaCloudTrail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


