/*
 * AWSAPICallViaCloudTrail
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SessionContext struct for SessionContext
type SessionContext struct {
	SessionIssuer SessionIssuer `json:"sessionIssuer"`
	Attributes Attributes `json:"attributes"`
}

// NewSessionContext instantiates a new SessionContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionContext(sessionIssuer SessionIssuer, attributes Attributes, ) *SessionContext {
	this := SessionContext{}
	this.SessionIssuer = sessionIssuer
	this.Attributes = attributes
	return &this
}

// NewSessionContextWithDefaults instantiates a new SessionContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionContextWithDefaults() *SessionContext {
	this := SessionContext{}
	return &this
}

// GetSessionIssuer returns the SessionIssuer field value
func (o *SessionContext) GetSessionIssuer() SessionIssuer {
	if o == nil  {
		var ret SessionIssuer
		return ret
	}

	return o.SessionIssuer
}

// GetSessionIssuerOk returns a tuple with the SessionIssuer field value
// and a boolean to check if the value has been set.
func (o *SessionContext) GetSessionIssuerOk() (*SessionIssuer, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SessionIssuer, true
}

// SetSessionIssuer sets field value
func (o *SessionContext) SetSessionIssuer(v SessionIssuer) {
	o.SessionIssuer = v
}

// GetAttributes returns the Attributes field value
func (o *SessionContext) GetAttributes() Attributes {
	if o == nil  {
		var ret Attributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SessionContext) GetAttributesOk() (*Attributes, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SessionContext) SetAttributes(v Attributes) {
	o.Attributes = v
}

func (o SessionContext) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sessionIssuer"] = o.SessionIssuer
	}
	if true {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableSessionContext struct {
	value *SessionContext
	isSet bool
}

func (v NullableSessionContext) Get() *SessionContext {
	return v.value
}

func (v *NullableSessionContext) Set(val *SessionContext) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionContext) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionContext(val *SessionContext) *NullableSessionContext {
	return &NullableSessionContext{value: val, isSet: true}
}

func (v NullableSessionContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


